/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#005c55',
        'primary-container': '#0d766e',
        'primary-fixed': '#9bf2e8',
        'primary-fixed-dim': '#7fd5cc',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00201d',
        'on-primary-fixed-variant': '#00504a',
        'on-primary-container': '#a3faef',
        'inverse-primary': '#7fd5cc',
        'secondary': '#565e74',
        'secondary-container': '#dae2fd',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        'on-secondary-container': '#5c647a',
        'tertiary': '#7d4200',
        'tertiary-container': '#a05600',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        'on-tertiary-container': '#ffe5d3',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#006a63',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3e4947',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'outline': '#6e7977',
        'outline-variant': '#bdc9c6',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'margin-mobile': '1rem',
        'gutter-mobile': '0.75rem',
        'margin': '1.5rem',
        'gutter': '1rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
