import os
import json
import random
import datetime
import urllib.request
import urllib.error
from typing import Dict, Any, List, Optional
from sqlalchemy.orm import Session

from .prompts import AFYACONNECT_SYSTEM_PROMPT
from .tools import AFYACONNECT_CLAUDE_TOOLS
from .care_navigation import determine_care_pathway, analyze_clinical_intake, SPECIALIST_ROSTER
from ..emergency.service import evaluate_clinical_safety
from ..location.service import find_nearby_facilities
from ..availability.service import get_facility_doctor_availability, validate_and_hold_slot
from ..notifications.service import dispatch_sms_notification
from ..database.models import Facility, CareRequest, CareRequestEvent, Appointment, RequestStatusEnum, UrgencyEnum, AppointmentStatusEnum


def execute_claude_tool(
    db: Session,
    tool_name: str,
    tool_input: Dict[str, Any],
    patient_info: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Dispatches tool calls generated by Claude during the agentic loop
    to real database queries and services.
    """
    if tool_name == "find_nearby_facilities":
        radius = tool_input.get("radiusKm", 5.0)
        pathway = tool_input.get("carePathway", "General Consultation")
        facilities = find_nearby_facilities(db, department=pathway, radius_km=radius)
        return {"success": True, "facilities": facilities, "count": len(facilities)}

    elif tool_name == "check_doctor_availability":
        fac_id = tool_input.get("facilityId", "f-agakhan")
        dept_code = tool_input.get("departmentCode", "OPD")
        avail = get_facility_doctor_availability(db, facility_id=fac_id, department_code=dept_code)
        return {"success": True, "availability": avail}

    elif tool_name == "create_appointment_request":
        chief = tool_input.get("chiefConcern", "Medical consultation")
        score = tool_input.get("triageScore", 2)
        urg = tool_input.get("urgency", "Standard")
        fac_id = tool_input.get("facilityId", "f-agakhan")
        slot = tool_input.get("preferredSlot", "Kesho 10:30 AM")
        req_id = f"req-{int(datetime.datetime.now(datetime.timezone.utc).timestamp() * 1000)}-{random.randint(100, 999)}"
        ref_num = f"#{random.randint(20000, 99999)}"

        care_req = CareRequest(
            id=req_id,
            referenceNumber=ref_num,
            patientId=patient_info.get("patientId", "pat-jane-1"),
            facilityId=fac_id,
            chiefConcern=chief,
            symptomDuration="2-3 days",
            secondarySymptoms="[]",
            triageScore=score,
            urgency=urg,
            clinicalSummary=f"Intake: {chief}. Triage: {score}/5.",
            verbatimTranscript=tool_input.get("verbatimTranscript", chief),
            preferredTime=slot,
            status=RequestStatusEnum.RECEIVED,
        )
        db.add(care_req)
        db.commit()
        return {"success": True, "careRequestId": care_req.id, "referenceNumber": ref_num}

    elif tool_name == "propose_appointment":
        req_id = tool_input.get("careRequestId")
        doc_name = tool_input.get("doctorName")
        slot_time = tool_input.get("slotTime")
        care_req = db.query(CareRequest).filter((CareRequest.id == req_id) | (CareRequest.referenceNumber == req_id)).first()
        if care_req:
            care_req.assignedDoctorName = doc_name
            care_req.assignedSlot = slot_time
            care_req.status = RequestStatusEnum.SLOT_PROPOSED
            db.commit()
            return {"success": True, "status": "SLOT_PROPOSED", "doctor": doc_name, "slot": slot_time}
        return {"success": False, "message": "Care request not found"}

    elif tool_name == "confirm_appointment":
        phone = tool_input.get("patientPhone", "+254712345678")
        doc_name = tool_input.get("doctorName", "Dr. Kamau")
        slot_time = tool_input.get("slotTime", "Kesho 10:30 AM")
        token = f"#AC-NBO-{random.randint(1000, 9999)}"
        return {"success": True, "tokenPass": token, "status": "CONFIRMED"}

    elif tool_name == "get_appointment_status":
        req_id = tool_input.get("careRequestId")
        care_req = db.query(CareRequest).filter((CareRequest.id == req_id) | (CareRequest.referenceNumber == req_id)).first()
        if care_req:
            return {"success": True, "status": care_req.status, "tokenPass": care_req.tokenPass}
        return {"success": False, "message": "Care request not found"}

    return {"success": False, "message": f"Unknown tool: {tool_name}"}


def call_anthropic_messages_api(
    messages: List[Dict[str, Any]],
    system_prompt: str = AFYACONNECT_SYSTEM_PROMPT,
    model: str = "claude-3-7-sonnet-20250219",
    api_key: Optional[str] = None,
) -> Optional[Dict[str, Any]]:
    api_key = api_key or os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return None

    url = "https://api.anthropic.com/v1/messages"
    payload = {
        "model": model,
        "max_tokens": 1200,
        "system": system_prompt,
        "tools": AFYACONNECT_CLAUDE_TOOLS,
        "messages": messages,
    }

    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "content-type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            if resp.status == 200:
                return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"Live Anthropic Claude API notice: {e}. Utilizing built-in clinical engine.")
        return None


def orchestrate_patient_turn(
    db: Session,
    patient_message: str,
    is_audio: bool = False,
    language_preference: str = "swa_eng",
    patient_info: Optional[Dict[str, Any]] = None,
    history: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """
    Core conversational orchestration layer.
    Connects patient conversation, tool calling, clinical safety evaluation,
    hospital queue generation, and bilingual feedback cards.
    """
    patient_info = patient_info or {"name": "Jane M.", "phone": "+254712345678", "location": "Westlands, Nairobi"}
    time_now = datetime.datetime.now().strftime("%I:%M %p")

    # 1. Emergency Safety Interception
    safety = evaluate_clinical_safety(patient_message)
    if safety["isEmergency"]:
        return {
            "text": safety["recommendedAction"],
            "responseMessage": safety["recommendedAction"],
            "isEmergency": True,
            "isEmergencyAlert": True,
            "triageScore": 5,
            "urgency": "EMERGENCY",
            "triageLevel": "Triage Level 5 (Emergency)",
            "dialectTag": "Dharura / Emergency Alert",
            "emergencyHotlines": safety.get("emergencyHotlines", []),
            "options": ["🚨 Piga 1199 (Red Cross)", "🏥 Tafuta Hospitali ya Dharura", "🚑 Piga 999 Ambulance"],
            "executedTools": [],
        }

    # 2. Clinical Intake Evaluation & Clarification Check
    intake = analyze_clinical_intake(patient_message, history=history, language_preference=language_preference)
    pathway = intake["pathway"]
    specialist = intake["specialist"]
    needs_clarification = intake["needsClarification"]

    req_id = f"req-{int(datetime.datetime.now(datetime.timezone.utc).timestamp() * 1000)}-{random.randint(100, 999)}"
    ref_num = f"#{random.randint(20000, 99999)}"

    # -------------------------------------------------------------------------
    # BRANCH A: Patient needs clarification (greeting or vague 1-word message)
    # Collects symptoms, duration, adult/child context BEFORE proposing doctor booking
    # -------------------------------------------------------------------------
    if needs_clarification:
        target_facility_id = specialist.get("facilityId", "f-agakhan")
        fac_obj = db.query(Facility).filter(Facility.id == target_facility_id).first()
        facility_name = fac_obj.name if fac_obj else "AfyaConnect Clinical Gateway"

        care_request = CareRequest(
            id=req_id,
            referenceNumber=ref_num,
            patientId=patient_info.get("patientId", "pat-jane-1"),
            facilityId=target_facility_id,
            assignedDoctorName=None,
            assignedSlot="Pending Triage",
            verbatimTranscript=patient_message,
            chiefConcern=patient_message[:60] if len(patient_message) > 60 else patient_message,
            symptomDuration="Initial intake",
            secondarySymptoms=json.dumps([pathway["department"], "Awaiting clinical details"]),
            triageScore=pathway["triageScore"],
            urgency=UrgencyEnum.URGENT if pathway["urgency"] == "URGENT" else UrgencyEnum.STANDARD,
            clinicalSummary=f"Intake in progress: {patient_message}. Proposed Department: {pathway['department']}.",
            flags=json.dumps(["Live AI Intake", "Clarification Active", "SHA Member"]),
            preferredTime="Pending triage",
            preferredDate="Pending triage",
            status=RequestStatusEnum.RECEIVED,
        )
        db.add(care_request)
        db.flush()

        timeline_steps = [
            (1, "CALL / CHAT MADE", "Patient initiated triage conversation via app / audio", time_now, True, False),
            (2, "Request received", "Intake logged and symptom assessment in progress", time_now, True, True),
            (3, "Hospital received request", "Hospital intake gateway received initial query", "Pending", False, False),
            (4, "Department identified", pathway["department"], "Pending", False, False),
            (5, "Doctor availability checked", "Awaiting clinical details before doctor allocation", "Pending", False, False),
            (6, "Time proposed", "Pending triage completion", "Pending", False, False),
            (7, "Patient confirmed", "Awaiting patient confirmation", "Pending", False, False),
            (8, "APPOINTMENT BOOKED", "Final booking token pending", "Pending", False, False),
        ]
        for step_num, title, desc, ts, comp, act in timeline_steps:
            db.add(CareRequestEvent(
                id=f"evt-{req_id}-{step_num}",
                careRequestId=care_request.id,
                stepNumber=step_num,
                title=title,
                description=desc,
                actor="Hospital Intake Gateway",
                timestampText=ts,
                isCompleted=comp,
                isActive=act,
            ))
        db.commit()

        if language_preference == "eng":
            requested_time_text = "Pending triage details"
            status_text = "Assessing symptoms"
            dialect_tag = "ENGLISH"
        elif language_preference == "swa":
            requested_time_text = "Inasubiri maelezo"
            status_text = "Inakaguliwa"
            dialect_tag = "KISWAHILI PEKEE"
        else:
            requested_time_text = "Pending triage details"
            status_text = "Checking symptoms"
            dialect_tag = "SWA + ENG CODE-SWITCH"

        feedback_card = {
            "type": "request_received",
            "department": pathway["department"],
            "requestedTime": requested_time_text,
            "statusText": status_text,
            "facilityName": facility_name,
            "requestId": ref_num,
        }

        return {
            "text": intake["clarificationMessage"],
            "responseMessage": intake["clarificationMessage"],
            "isEmergency": False,
            "isEmergencyAlert": False,
            "triageScore": pathway["triageScore"],
            "urgency": pathway["urgency"],
            "triageLevel": f"Triage Level {pathway['triageScore']}",
            "dialectTag": dialect_tag,
            "feedbackCard": feedback_card,
            "nearbyFacilities": [],
            "careRequestId": care_request.id,
            "referenceNumber": care_request.referenceNumber,
            "options": intake["clarificationOptions"],
            "createdCareRequest": {
                "id": care_request.id,
                "referenceNumber": care_request.referenceNumber,
                "chiefConcern": care_request.chiefConcern,
                "urgency": care_request.urgency,
                "status": care_request.status,
                "facilityId": care_request.facilityId,
                "assignedDoctorName": None,
                "assignedSlot": "Pending Triage",
            },
            "executedTools": [
                {"toolName": "analyze_clinical_intake", "success": True, "needsClarification": True, "pathway": pathway["department"]},
                {"toolName": "create_appointment_request", "success": True, "requestId": ref_num, "status": "RECEIVED"},
            ],
        }

    # -------------------------------------------------------------------------
    # BRANCH B: Clinical intake complete -> Match specific specialist & propose slot
    # -------------------------------------------------------------------------
    target_facility_id = specialist.get("facilityId", "f-agakhan")
    lead_doc = specialist.get("doctorName", "Dr. Wanjiku Kamau")
    specialty_name = specialist.get("specialist", pathway["suggestedSpecialty"])

    # 3. Location & Nearby Facilities
    nearby = find_nearby_facilities(db, department=pathway["department"], radius_km=5.0)
    primary_facility = next((f for f in nearby if f["id"] == target_facility_id), None)
    if not primary_facility:
        fac_obj = db.query(Facility).filter(Facility.id == target_facility_id).first()
        if fac_obj:
            primary_facility = {
                "id": fac_obj.id,
                "name": fac_obj.name,
                "subCounty": fac_obj.subCounty,
                "distanceKm": fac_obj.distanceKm,
                "driveTime": f"~{int(fac_obj.distanceKm * 4)} min drive",
                "leadDoctor": lead_doc,
                "earliestSlot": "Leo 3:30 PM",
            }
        else:
            primary_facility = nearby[0] if nearby else {
                "id": "f-agakhan",
                "name": "Aga Khan Univ. Hospital",
                "subCounty": "Parklands Sub-County",
                "distanceKm": 1.4,
                "driveTime": "~6 min drive",
                "leadDoctor": lead_doc,
                "earliestSlot": "Leo 3:30 PM",
            }

    # 4. Availability Check for Specific Specialist
    avail = get_facility_doctor_availability(db, primary_facility["id"], pathway["departmentCode"])
    matched_doc = next(
        (
            d for d in avail.get("availableDoctors", [])
            if lead_doc.lower() in d.get("doctorName", "").lower()
            or d.get("doctorName", "").lower() in lead_doc.lower()
        ),
        None,
    )
    if matched_doc:
        lead_doc = matched_doc.get("doctorName", lead_doc)
        if matched_doc.get("freeSlots"):
            earliest_slot = matched_doc["freeSlots"][0]
        elif matched_doc.get("slots"):
            earliest_slot = matched_doc["slots"][0]
        else:
            earliest_slot = avail.get("earliestAvailableSlot", "Leo 3:30 PM")
    elif avail.get("availableDoctors") and avail["availableDoctors"][0].get("freeSlots"):
        earliest_slot = avail["availableDoctors"][0]["freeSlots"][0]
        lead_doc = avail["availableDoctors"][0]["doctorName"]
    elif avail.get("availableDoctors") and avail["availableDoctors"][0].get("slots"):
        earliest_slot = avail["availableDoctors"][0]["slots"][0]
        lead_doc = avail["availableDoctors"][0]["doctorName"]
    else:
        earliest_slot = avail.get("earliestAvailableSlot", "Leo 3:30 PM")

    # 5. Create Structured Care Request in DB (Case #10482 style)
    care_request = CareRequest(
        id=req_id,
        referenceNumber=ref_num,
        patientId=patient_info.get("patientId", "pat-jane-1"),
        facilityId=primary_facility["id"],
        assignedDoctorName=lead_doc,
        assignedSlot=earliest_slot,
        verbatimTranscript=patient_message,
        chiefConcern=patient_message[:60] if len(patient_message) > 60 else patient_message,
        symptomDuration="2-3 days",
        secondarySymptoms=json.dumps([pathway["department"], specialty_name]),
        triageScore=pathway["triageScore"],
        urgency=UrgencyEnum.URGENT if pathway["urgency"] == "URGENT" else UrgencyEnum.STANDARD,
        clinicalSummary=f"Intake: {patient_message}. Specialist: {specialty_name} ({lead_doc}). Department: {pathway['department']}. Triage: {pathway['triageScore']}/5.",
        flags=json.dumps(["Live AI Intake", "Specialist Matched", "Auto-Location Active", "SHA Member"]),
        preferredTime=earliest_slot,
        preferredDate="Kesho, Jumanne 24 Sept",
        status=RequestStatusEnum.RECEIVED,
    )
    db.add(care_request)
    db.flush()

    # Initial 8-step timeline events
    timeline_steps = [
        (1, "CALL / CHAT MADE", "Patient initiated triage conversation via app / audio", time_now, True, False),
        (2, "Request received", "Triage intake logged and pre-screened", time_now, True, False),
        (3, "Hospital received request", f"{primary_facility['name']} intake and triage queue synced", time_now, True, True),
        (4, "Department identified", f"{pathway['department']} ({specialty_name})", time_now, True, False),
        (5, "Doctor availability checked", f"{lead_doc} calendar check verified", time_now, True, False),
        (6, "Time proposed", f"Slot {earliest_slot} proposed to patient", time_now, True, True),
        (7, "Patient confirmed", "Awaiting patient confirmation", "Pending", False, False),
        (8, "APPOINTMENT BOOKED", "Final booking token pending", "Pending", False, False),
    ]
    for step_num, title, desc, ts, comp, act in timeline_steps:
        db.add(CareRequestEvent(
            id=f"evt-{req_id}-{step_num}",
            careRequestId=care_request.id,
            stepNumber=step_num,
            title=title,
            description=desc,
            actor="Hospital Intake Gateway",
            timestampText=ts,
            isCompleted=comp,
            isActive=act,
        ))
    db.commit()

    # 6. Bilingual Response Generation (Live Claude API with Local Clinical Engine Fallback)
    lower = patient_message.lower()
    live_claude_used = False
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if api_key:
        claude_messages = []
        if history:
            for h in history[-4:]:
                role = "user" if h.get("sender") in ["patient", "user"] else "assistant"
                claude_messages.append({"role": role, "content": h.get("text", "")})
        claude_messages.append({"role": "user", "content": patient_message})

        live_res = call_anthropic_messages_api(claude_messages, api_key=api_key)
        if live_res and "content" in live_res:
            for block in live_res["content"]:
                if block.get("type") == "text" and block.get("text"):
                    ai_text = block["text"]
                    live_claude_used = True
                    break

    # Format slot and date labels strictly according to language preference
    is_tomorrow = "kesho" in earliest_slot.lower() or "tomorrow" in earliest_slot.lower()
    clean_slot_time = earliest_slot.replace("Leo ", "").replace("Kesho ", "").replace("Today ", "").replace("Tomorrow ", "")

    if language_preference == "eng":
        dialect_tag = "ENGLISH"
        date_label = "Tomorrow, Tuesday 24 Sept" if is_tomorrow else "Today, Sunday 20 Sept"
        time_label = f"Tomorrow at {clean_slot_time}" if is_tomorrow else f"Today at {clean_slot_time}"
        status_label = "Verified Slot"
    elif language_preference == "swa":
        dialect_tag = "KISWAHILI PEKEE"
        date_label = "Kesho, Jumanne 24 Sept" if is_tomorrow else "Leo, Jumapili 20 Sept"
        time_label = f"Kesho {clean_slot_time}" if is_tomorrow else f"Leo {clean_slot_time}"
        status_label = "Nafasi Imethibitishwa"
    else:
        dialect_tag = "SWA + ENG CODE-SWITCH"
        date_label = "Tomorrow, Tuesday 24 Sept" if is_tomorrow else "Leo, Jumapili 20 Sept"
        time_label = f"Kesho at {clean_slot_time}" if is_tomorrow else f"Leo at {clean_slot_time}"
        status_label = "Verified Slot"

    if not live_claude_used:
        if language_preference == "eng":
            ai_text = (
                f"I understand what you are experiencing. Based on your symptoms, I recommend a consultation with {specialty_name} ({lead_doc}) "
                f"in the {pathway['department']} department at {primary_facility['name']}. "
                f"{pathway['explanationEnglish']} A verified slot is available {time_label}. "
                f"Would you like to book this appointment?"
            )
        elif language_preference == "swa":
            ai_text = (
                f"Kulingana na maelezo ya dalili zako, ninapendekeza mashauriano na {specialty_name} ({lead_doc}) "
                f"katika kitengo cha {pathway['department']} hapa {primary_facility['name']}. "
                f"{pathway['explanationSwahili']} Nafasi ya daktari inapatikana {time_label}. "
                f"Je, ungependa kuthibitisha miadi hii?"
            )
        else:
            user_has_swahili = any(sw in lower for sw in ["nimekuwa", "nahisi", "tumbo", "kichwa", "daktari", "kesho", "leo", "homa", "mtoto", "masikio", "jino", "ngozi", "kuona"])
            if not user_has_swahili:
                ai_text = (
                    f"Based on your description, I recommend consulting with {specialty_name} ({lead_doc}) "
                    f"in {pathway['department']} at {primary_facility['name']}. "
                    f"{pathway['explanationEnglish']} A slot is available {time_label}. Would you like to book this appointment?"
                )
            else:
                ai_text = (
                    f"Pole sana, nimekuelewa vizuri: {pathway['explanationSwahili']} "
                    f"Ninapendekeza {specialty_name} ({lead_doc}) katika hospitali ya {primary_facility['name']}. "
                    f"Kuna nafasi {time_label}. Je, ungependa kuthibitisha miadi hii?"
                )

    # 7. Feedback Card Data
    feedback_card = {
        "type": "doctor_availability",
        "department": pathway["department"],
        "doctorName": lead_doc,
        "date": date_label,
        "time": time_label,
        "facilityName": primary_facility["name"],
        "requestId": ref_num,
        "statusText": status_label,
    }

    # 8. Nearby Facilities Options Summary for Patient
    nearby_options = [
        {
            "name": f["name"],
            "distance": f"{f['distanceKm']} km",
            "distanceKm": f["distanceKm"],
            "driveTime": f["driveTime"],
            "earliestSlot": f["earliestSlot"],
            "leadDoctor": f["leadDoctor"],
            "facilityId": f["id"],
            "id": f["id"],
            "subCounty": f.get("subCounty", "Parklands Sub-County"),
        }
        for f in nearby[:3]
    ]

    if language_preference == "eng":
        response_options = [
            f"Confirm Slot: {lead_doc} • {time_label}",
            "📍 Check Nearby Facilities",
            "🩺 I need a doctor today",
        ]
    elif language_preference == "swa":
        response_options = [
            f"Thibitisha: {lead_doc} • {time_label}",
            "📍 Tazama Vituo Vilivyo Karibu",
            "🩺 Nahitaji daktari leo",
        ]
    else:
        response_options = [
            f"Confirm Slot: {lead_doc} • {time_label}",
            "📍 Ona Vituo / Other Options",
            "🩺 Nahitaji daktari leo",
        ]

    return {
        "text": ai_text,
        "responseMessage": ai_text,
        "isEmergency": False,
        "isEmergencyAlert": False,
        "triageScore": pathway["triageScore"],
        "urgency": pathway["urgency"],
        "triageLevel": f"Triage Level {pathway['triageScore']}",
        "dialectTag": dialect_tag,
        "feedbackCard": feedback_card,
        "nearbyFacilities": nearby_options,
        "careRequestId": care_request.id,
        "referenceNumber": care_request.referenceNumber,
        "options": response_options,
        "createdCareRequest": {
            "id": care_request.id,
            "referenceNumber": care_request.referenceNumber,
            "chiefConcern": care_request.chiefConcern,
            "urgency": care_request.urgency,
            "status": care_request.status,
            "facilityId": care_request.facilityId,
            "assignedDoctorName": care_request.assignedDoctorName,
            "assignedSlot": care_request.assignedSlot,
        },
        "executedTools": [
            {"toolName": "analyze_clinical_intake", "success": True, "needsClarification": False, "specialist": lead_doc},
            {"toolName": "find_nearby_facilities", "success": True, "count": len(nearby)},
            {"toolName": "check_doctor_availability", "success": True, "doctor": lead_doc, "slot": earliest_slot},
            {"toolName": "create_appointment_request", "success": True, "requestId": ref_num},
        ],
    }
